export const THE_NEW_PLACE_GUIDES = Object.freeze({
  bud: Object.freeze({ name: 'Bud Tendar', accent: '#C9A84C' }),
  sunny: Object.freeze({ name: 'Sunny Day', accent: '#FF7F5C' }),
  larry: Object.freeze({ name: 'Lucky Larry', accent: '#C17A3A' }),
  herb: Object.freeze({ name: 'Herb N. Spices', accent: '#4ECDC4' }),
  mary: Object.freeze({ name: 'Mary Jayne', accent: '#B088B0' }),
  stoner: Object.freeze({ name: 'S.T.O.N.E.R.', accent: '#C9A84C' }),
  unit: Object.freeze({ name: 'Unit', accent: '#888888' }),
  tool: Object.freeze({ name: 'Tool', accent: '#C9A84C' }),
})

const LINES = Object.freeze({
  bud: Object.freeze({ opening: 'One week. Keep the place standing. Start with the problem in front of you.', decision: 'That is the call. Now we see what the store does with it.', report: 'Same facts, different emphasis. Pick the version you can defend later.', inconsistency: 'That framing does not match the way you handled this problem before.', inspector: 'Inspector is here. The week already decided what they are going to notice.', completion: 'Seven days. The numbers are what they are. The place made it through.' }),
  sunny: Object.freeze({ opening: 'Okay. New place, new week, manageable amount of chaos.', decision: 'Decision made. I am emotionally invested in seeing where that lands.', report: 'All three versions are about the same day. Choose the story you are willing to keep telling.', inconsistency: 'Oh, that is different from how we framed this before. That may come back.', inspector: 'They are here. We knew this day was coming. Mostly.', completion: 'We made it to Sunday. The place is still standing, which feels important.' }),
  larry: Object.freeze({ opening: 'I knew a shop with an opening week like this once. Different state. Same paperwork smell.', decision: 'That is a management decision. Those have a way of showing up again three days later.', report: 'Write the report for Friday-you, not Tuesday-you. Friday-you has questions.', inconsistency: 'There it is. Two explanations for the same kind of problem. Somebody will notice.', inspector: 'Inspector day. I have stories. None of them are useful right now.', completion: 'Week is over. I have seen worse. I have also seen buildings physically on fire, so adjust for scale.' }),
  herb: Object.freeze({ opening: 'Seven days, finite state, measurable consequences. I find this promising.', decision: 'Decision recorded. We can now observe the downstream effect instead of guessing.', report: 'The facts are fixed. Only the analytical frame is changing.', inconsistency: 'The reporting pattern is no longer internally consistent. That is measurable.', inspector: 'Inspection focus derived from the weakest current state. I appreciate the logic, if not the timing.', completion: 'Week complete. We now have an actual outcome instead of a theory about one.' }),
  mary: Object.freeze({ opening: 'We only need to handle one day at a time. Monday first.', decision: 'That choice is made. Watch what it changes before deciding whether it was good or bad.', report: 'Keep the facts intact. Choose the framing that still feels accurate tomorrow.', inconsistency: 'This explanation and the earlier one do not sit together cleanly.', inspector: 'The inspector is looking at the part of the week that needed the most care.', completion: 'It is Sunday. Whatever the score says, the full week is here to learn from.' }),
  stoner: Object.freeze({ opening: 'I have been here a while. I know how things worked before. We are about to discover whether that information remains useful.', decision: 'Decision recorded. I have predictions. I am not treating them as results.', report: 'I can see all three positions on the report. Choose one you can defend when the inspector reads it.', inconsistency: 'The record now contains two different framings of the same kind of problem. I find that notable.', inspector: 'The inspector is here. I have been preparing for this with a level of enthusiasm I recognize may be unusual.', completion: 'The place is still standing. That was the goal. I think we did alright.' }),
  unit: Object.freeze({ opening: 'Week initialized. Monday active.', decision: 'Decision recorded. State updated.', report: 'Report frame required.', inconsistency: 'Report inconsistency recorded.', inspector: 'Inspection resolved from current state.', completion: 'Week complete. Summary recorded.' }),
  tool: Object.freeze({ opening: 'Start with Monday. Make one decision, review the result, then file the day.', decision: 'State updated from the selected decision.', report: 'Choose a factual report frame. The underlying result will not change.', inconsistency: 'This frame conflicts with a prior frame for the same issue type.', inspector: 'Inspector focus is calculated from the week state, not generated by narration.', completion: 'The seven-day run is complete and ready for replay.' }),
})

function keyFor(value) {
  const key = typeof value === 'string' ? value.trim().toLowerCase() : ''
  return Object.hasOwn(THE_NEW_PLACE_GUIDES, key) ? key : 'bud'
}

async function resolveStore(explicitStore) {
  if (explicitStore) return explicitStore
  const module = await import('../../../lib/localStore.js')
  return module.localStore
}

export function theNewPlaceGuideMeta(value) {
  const key = keyFor(value)
  return { key, ...THE_NEW_PLACE_GUIDES[key] }
}

export function theNewPlaceGuideLine(guideKey, moment) {
  const key = keyFor(guideKey)
  return LINES[key][Object.hasOwn(LINES[key], moment) ? moment : 'opening']
}

export function theNewPlaceGuideMoment(previousRun, nextRun) {
  if (!previousRun) return 'opening'
  const latest = nextRun?.history?.at?.(-1)
  if (!latest) return 'opening'
  if (latest.type === 'decision') return 'decision'
  if (latest.type === 'report') return latest.inconsistent ? 'inconsistency' : 'report'
  if (latest.type === 'inspector') return 'inspector'
  if (latest.type === 'completion') return 'completion'
  return 'decision'
}

export async function readSelectedTheNewPlaceGuide({ store = null, userId = null, devMode = false } = {}) {
  if (devMode) return theNewPlaceGuideMeta('sunny')
  const localStore = await resolveStore(store)
  let resolvedUserId = typeof userId === 'string' ? userId.trim() : ''
  if (!resolvedUserId) {
    const auth = await localStore.auth.getUser()
    resolvedUserId = auth?.data?.user?.id || ''
  }
  if (!resolvedUserId) return theNewPlaceGuideMeta('bud')
  const result = await localStore.from('user_profiles').select('guide_selected').eq('user_id', resolvedUserId).maybeSingle()
  if (result?.error) throw result.error
  return theNewPlaceGuideMeta(result?.data?.guide_selected || 'bud')
}
