import { STARTER_LANDS_PROLOGUE } from './starterLandsPrologue.js'
import { SABLE_MERROW } from './starterLandsArmory.js'

export const STARTER_BLOCKS = Object.freeze([
  Object.freeze({
    id: STARTER_LANDS_PROLOGUE.id,
    version: 1,
    family: 'anchor',
    chapter: 0,
    location: 'Mossgate Wayhouse',
    pacingRole: 'orientation',
    importance: 'required',
    estimatedReadSeconds: 230,
    baseWeight: 1,
    repeatDecay: 0,
    requiresAll: Object.freeze([]),
    requiresAny: Object.freeze([]),
    forbids: Object.freeze([]),
    content: STARTER_LANDS_PROLOGUE.paragraphs,
    tags: Object.freeze(['starter', 'prologue', 'eliza']),
  }),
  Object.freeze({
    id: 'starter:armory:arrival',
    version: 1,
    family: 'anchor',
    chapter: 0,
    location: SABLE_MERROW.shop,
    pacingRole: 'exploration',
    importance: 'required',
    estimatedReadSeconds: 75,
    baseWeight: 1,
    repeatDecay: 0,
    requiresAll: Object.freeze(['player.ancestryId']),
    requiresAny: Object.freeze([]),
    forbids: Object.freeze([]),
    content: SABLE_MERROW.introduction,
    tags: Object.freeze(['starter', 'sable', 'armory']),
  }),
  Object.freeze({
    id: 'starter:departure:road',
    version: 1,
    family: 'reactive',
    chapter: 0,
    location: 'North Road',
    pacingRole: 'transition',
    importance: 'required',
    estimatedReadSeconds: 55,
    baseWeight: 1,
    repeatDecay: 0,
    requiresAll: Object.freeze(['player.weaponId', 'player.backgroundId']),
    requiresAny: Object.freeze([]),
    forbids: Object.freeze([]),
    content: Object.freeze([
      `Mossgate narrows behind you from buildings to roofs to a final crooked signpost. Ahead, the road begins climbing toward the Goblin Highlands.`,
      `The easy part of the journey is over. The interesting part has not yet admitted it is interested in you.`,
    ]),
    tags: Object.freeze(['starter', 'departure']),
  }),
])
