export const STARTER_ANCESTRIES = Object.freeze([
  Object.freeze({
    id: 'human',
    label: 'Human',
    hook: 'People of roads, reinvention, and places that were not towns until somebody decided they were.',
    sections: Object.freeze([
      ['Where people come from', `Humans do not have one homeland. They have too many. There are old river cities where families point to the same cracked doorstep for nine generations, hill villages built around watchtowers no one remembers needing, market towns that started as three wagons beside a well, and human neighborhoods inside dwarf holds, elven treaty lands, and gnome districts. Mossgate itself is a very human kind of place. Nobody founded it in the heroic sense. People stopped here. Somebody built an inn. Somebody else built a smithy because the inn's horses kept throwing shoes. A merchant added a storehouse. A tax collector arrived, was ignored, and eventually opened a bakery. Two hundred years later everybody pretends this was the plan.`],
      ['History', `Human kingdoms have risen and collapsed across the Reach often enough that historians eventually stopped numbering them and started using descriptions such as The Red One, The Kingdom With All The Swans, and That Seventy-Two-Year Administrative Mistake Near Bellwater. What survived was rarely the crown. Roads survived. Wells survived. Market charters survived. Recipes survived. Families survived. So did a habit of borrowing whatever worked from whoever was nearby. A human soldier may carry a dwarf-made buckle, drink from an elf-fired cup, keep a gnome charm in one pocket, and curse in four languages without considering any of this unusual.`],
      ['Community and values', `There is no single human value system, but many communities admire usefulness, improvisation, hospitality, personal reputation, and surviving embarrassing circumstances without making everyone else listen to the entire story. Roadside hospitality is especially strong in dangerous country. A stranger may be offered stew, a chair, local gossip, and a completely unsolicited warning about the bridge north of town before anyone asks their name. Humans also have tremendous cultural faith in signs: ROAD CLOSED. DO NOT FEED THE WELL. ABSOLUTELY NO SPELLCASTING IN THE CHEESE ROOM. The existence of a sign implies that somebody did the thing. Usually recently.`],
      ['Green culture', `Human green traditions are as inconsistent as everything else. In some towns, passing a carved smoke-pipe around a story circle is a mark of hospitality. In others, festival-goers carry bundles of fantasy leaf that release colored clouds shaped like local saints, monsters, or once, due to a disputed batch, municipal officials. Mossgate's most famous green holiday is the Feast of the Long Nap, which allegedly commemorates a legendary healer and in practice commemorates people forgetting where they left the parade.`],
      ['Other peoples', `Dwarves sometimes find humans reckless with permanence. Elves sometimes admire human urgency and sometimes find it exhausting. Gnomes appreciate humans as neighbors, customers, and people who will press a mysterious button after being told not to. Goblin-human relations depend entirely on where you are. Border villages trade with goblin families regularly. Other settlements tell frightening stories while buying goblin-made traps through three middlemen and pretending not to notice the stamp underneath.`],
      ['In play', `The stereotype is that humans are ordinary. They are not. Their advantage is unpredictability. A human can plausibly have grown up almost anywhere, around almost anyone, doing almost anything. In play, Humans are Adaptable: especially good at reading unfamiliar social situations and turning unexpected circumstances into usable choices. This can reveal human-favored social observations or improvisational options. It never means automatic success.`],
      ['Your Human', `None of this tells me who you are. You may come from an old family or have no idea who your grandparents were. You may love crowded cities, hate them, have grown up under a mountain, or spent childhood moving between wagons. Your ancestry gives your character history to stand inside. You decide what they did with it.`],
    ]),
  }),
  Object.freeze({
    id: 'dwarf',
    label: 'Dwarf',
    hook: 'People who believe anything worth building should still be there after the argument about how to build it is over.',
    sections: Object.freeze([
      ['Homelands', `Dwarves are associated with mountains because mountains are difficult to move, slow to change, full of hidden structure, and capable of killing the overconfident without raising their voice. Dwarves consider the comparison flattering. Most dwarf communities are built around holds, quarry towns, deep-road stations, cliff settlements, and stone cities, but there are dwarf farming valleys, river engineers, urban guild families, brewers, archivists, actors, smugglers, cooks, judges, and an alarming number of people who will happily explain why the wall you are leaning against is badly made.`],
      ['Stone as memory', `The oldest holds are not simply cities. They are records. A doorway may preserve the chisel marks of the apprentice who cut it six hundred years ago. A public stair can be widened rather than replaced because generations remember who carried wounded miners up the original steps. Dwarves often speak of stone as memory. Usually they do not mean every rock is secretly talking. They mean material records decisions. A cracked brace tells you somebody overloaded it. A polished threshold tells you thousands of feet crossed there. A repaired wall tells you something happened and somebody thought the place was worth keeping.`],
      ['History and values', `Dwarf history is full of holds that survived wars their kings did not, treaties that outlived the people who signed them, and engineering projects begun by one generation because they knew another would have to finish them. This produces patience. It also produces grudges with extraordinary documentation. Many dwarf communities admire durability, craft, responsibility, memory, and showing up when you said you would. Dwarf humor thrives on understatement, elaborate insults delivered without changing facial expression, and stories told so slowly that the victim realizes three minutes too late they have been the joke since the first sentence.`],
      ['Green culture', `Dwarf green traditions are famously overengineered. Some holds carve ceremonial smoke vessels directly into communal stone tables. One Deep-Road lodge owns a pipe with a mouthpiece for twelve people, a carved dragon head, two pressure gauges that measure nothing anyone understands, and a brass plaque reading DO NOT ASK BORIN WHAT HAPPENED IN 611. Nobody asks Borin. Traveling circles tell stories over enchanted fantasy leaf whose smoke settles into old masonry and briefly makes previous repair marks glow. Whether this is magic, tradition, exaggeration, or an extremely committed joke depends on whom you ask.`],
      ['Other peoples', `Humans can seem alarmingly willing to call something finished because it remained upright through lunch. Elves and dwarves have old disagreements about preservation: dwarves often preserve by reinforcing, elves by allowing a place to change without losing its identity. Gnomes are either delightful collaborators or a direct assault on the concept of a final blueprint. Goblin engineering drives dwarves insane because it frequently works. A goblin bridge may violate six respectable principles of construction, contain three unrelated chair legs, and remain standing forty years out of what appears to be spite.`],
      ['In play', `People often assume dwarves hate change. Most do not. They hate careless change. In play, Dwarves are Stonewise and steady under force. They may automatically notice obvious structural weakness, stonework history, load problems, repairs, tunnels, or evidence in built terrain that others need to inspect deliberately. This is not trap immunity and it is not magical knowledge of every rock.`],
      ['Your Dwarf', `Perhaps you were raised in a deep hold and know every family story. Perhaps you grew up in a mixed town and are sick of strangers asking what mountain you came from. Maybe you are traditional. Maybe you left because tradition felt like living in somebody else's memory. Your ancestry gives you inherited context. Your character decides whether to carry it, argue with it, reinvent it, or pretend not to care until somebody insults the bridge.`],
    ]),
  }),
  Object.freeze({
    id: 'elf',
    label: 'Elf',
    hook: 'People who learned that long memory is useful only if you still notice what is happening now.',
    sections: Object.freeze([
      ['Homelands', `Elves are often described as ancient, mysterious, graceful, woodland, moon-touched, impossible to hurry, and annoyingly good at standing somewhere scenic. Elves themselves describe this as evidence that other people need better hobbies. There are old communities beneath living canopies, certainly, but also cliff towns, river wards, night markets, orchard settlements, lighthouse families, traveling theatre companies, scholars in human cities, gardeners inside dwarf holds, and urban elves who have not touched an ancient forest in three generations and would like strangers to stop asking whether they can talk to trees. Some can. The trees are not always worth talking to.`],
      ['Living places', `Many traditional settlements are built around living boundaries rather than fixed walls. A village may follow the edge of a grove, the seasonal path of a river, or the migration of enormous silver moths that arrive every seventh year and eat absolutely everything except pears. Walkways bend around old trunks. Homes are rebuilt as roots rise. Bridges may move because a river changed course rather than forcing the water back into somebody's grandfather's preferred arrangement. To outsiders this can look temporary. To elves it can be another kind of permanence. The place survives because it knows how to change.`],
      ['History and values', `Elven history is unusually dangerous because elves sometimes live long enough to remember people everybody else has turned into statues. That does not make their history more accurate. Witnesses lie. Families disagree. Heroes become embarrassing with age. Many communities therefore maintain layered histories: written records, songs, witness accounts, landscape markers, family stories, and formal spaces where contradictory versions are allowed to remain contradictory. Many place importance on attention, stewardship, memory, chosen obligations, and the idea that rushing past something does not mean you understood it.`],
      ['Green culture', `Elven green traditions tend toward ceremony, art, and spectacular unnecessary beauty. In some forest houses, enchanted fantasy-herb smoke is coaxed into drifting animals, ancestral symbols, old constellations, or extremely flattering versions of the storyteller. Festival circles may fill clearings with luminous green mist that hums with the musicians and develops a tendency to follow whoever brought snacks. One famous enclave breeds a magical vine called Whisperweed that repeats the last compliment spoken near it for several days. It was intended to encourage kindness. It created a thriving business in strategically placed potted plants.`],
      ['Other peoples', `Humans fascinate and exhaust elves in roughly equal measure. Dwarves and elves share concern for continuity but disagree on method. Gnomes are difficult to describe because any statement about gnomes causes at least one nearby gnome to immediately become an exception. Goblin relations are complicated: some border communities have traded with highland clans for centuries, while others remember raids, broken pacts, or damaged forests. An elf may therefore have older stories about goblins without having one universal opinion of them.`],
      ['In play', `People often assume elves are calm. Some are. Some are merely quiet while furious. Long memory does not create wisdom automatically; it creates more material from which wisdom might, with luck, be assembled. In play, Elves have keen distance vision and strong low-light navigation. They may notice distant motion, visual irregularities, old living boundaries, faint trail changes, or details in dim environments earlier than others. Observation is not omniscience. An elf can see a distant figure clearly and still have no idea why that figure is wearing a bucket.`],
      ['Your Elf', `Maybe you were raised by people who treat history as sacred. Maybe your family moved into a human city and woodland mysticism is something your grandmother sends you articles about. Maybe you are patient. Maybe you are so impatient your relatives use you as a cautionary tale. Your ancestry offers context, tensions, habits, and possible knowledge. It does not choose your personality.`],
    ]),
  }),
  Object.freeze({
    id: 'gnome',
    label: 'Gnome',
    hook: 'People most likely to see an impossible mechanism and ask whether anyone has tried making it slightly more impossible.',
    sections: Object.freeze([
      ['Homelands', `Gnomes have a reputation for invention. This is unfair. Some are painters, farmers, teachers, cooks, diplomats, undertakers, sailors, archivists, thieves, healers, shepherds, or professional people-who-explain-to-inventors-why-the-building-is-on-fire. The reputation persists because many gnome communities treat curiosity as a civic resource. Settlements often appear where people, materials, roads, or magic collide: hinge-towns around trade gates, canal communities full of lifts and locks, marsh workshops on adjustable stilts, and dense quarters where bakeries share walls with lens grinders, printers, clockmakers, herbalists, costume makers, and one business whose sign simply reads PROBLEMS SOLVED / NEW PROBLEMS AVAILABLE.`],
      ['Curiosity', `A child who takes apart the household clock may be punished. The punishment may involve putting it back together, documenting the failure, presenting findings at dinner, and explaining why there are now two leftover springs and a noise coming from the pantry. Gnome families and guilds often keep shelves of failed prototypes. Failure is treated less as shame than evidence. A broken device may be tagged with the date, intended purpose, reason it failed, and whether the resulting noise frightened livestock. Some workshops ring a little bell when an experiment works. Others ring a much larger bell when it does not, so everybody knows to move away from the windows.`],
      ['History and values', `Gnome history is full of inventions everybody remembers and inventors nobody can agree about. A famous lifting engine may be credited to one genius in a schoolbook, seven cousins in a family archive, and a tavern owner according to a note found inside the engine itself. Their bridge repairs, signal systems, locks, pumps, lenses, printing mechanisms, and navigation tools connected communities after old road networks began failing. They also produced several spectacular disasters. The disasters are included in the official histories. Often with diagrams. Many gnome cultures admire curiosity, wit, repairability, sharing useful knowledge, and refusing to accept “because that is how it works” as a complete explanation.`],
      ['Green culture', `Gnome fantasy weed culture is exactly what you are imagining and somehow less sensible. There are carved pipes with mechanical shutters, glass contraptions with seventeen chambers and a bell that rings when the device believes you are overthinking things, enchanted smoke wheels that form tiny weather systems over a table, and herb cabinets labeled CALM, FOCUS, SINGING, DO NOT STORE NEAR CLOCKS, and WE STILL DO NOT KNOW WHAT THIS ONE WANTS. One famous salon keeps a ceremonial smoking machine called The Moderate Decision. It is the size of a wardrobe. No part of it appears moderate.`],
      ['Other peoples', `Humans tend to adopt gnome inventions enthusiastically and maintenance schedules philosophically. Dwarves and gnomes can collaborate brilliantly until they disagree about whether a machine should last one hundred years or be rebuilt every six months because the new version has more interesting levers. Elves appreciate gnome attention to patterns and become uneasy when that attention turns toward systems they believe should remain alive rather than optimized. Goblins are the great engineering irritation: a gnome may spend a week designing an elegant alarm; a goblin may tie a spoon to a boot, tie the boot to a goat, and somehow achieve the same practical result.`],
      ['In play', `People assume every gnome wants to build something. Many do not. The deeper tendency is curiosity, not machinery. A gnome historian may dismantle an official story the way an engineer dismantles a clock. In play, Gnomes have mechanism sense and sensitivity to magical irregularities. They may notice how alarms, traps, improvised devices, locks, odd magical systems, and badly behaved mechanisms fit together. They receive extra context around constructed or magical puzzles without automatically receiving the solution.`],
      ['Your Gnome', `Maybe you grew up in a workshop and hated every minute. Maybe you adore machines. Maybe your curiosity is aimed at people, history, food, crime, weather, or why goblins keep putting shoes where shoes should not be. Your ancestry gives you a culture that respects questions. Which questions your character cannot leave alone are yours to decide.`],
    ]),
  }),
])

export function ancestryById(id) {
  return STARTER_ANCESTRIES.find((item) => item.id === id) || null
}
