export const STARTER_LANDS_PROLOGUE = Object.freeze({
  id: 'starter:prologue:reach',
  title: 'Before the Goblin Highlands',
  paragraphs: Object.freeze([
    `Before we decide who you are, you should probably know where you have made the questionable decision to exist.`,
    `This is the Reach. Nobody agrees where the Reach begins. Cartographers put the boundary wherever their employer stops paying them. Dwarves say it begins at the first stone road worth trusting. Elves insist a place is not truly part of the Reach until the old trees have learned its name. Gnomes have produced seventeen competing definitions, six diagrams, and one small brass machine that points toward the Reach no matter where you stand. Humans mostly shrug and ask whether the road ahead has an inn.`,
    `The Reach is a quilt of old roads, young towns, stubborn kingdoms, half-forgotten ruins, trading posts, river cities, deep holds, forest enclaves, impossible little workshops, and wilderness that has never signed anything agreeing to behave. Humans, dwarves, elves, gnomes, goblins, and stranger people have crossed one another's paths here for longer than anyone can remember accurately. They trade, marry, feud, borrow tools, steal recipes, mispronounce one another's holidays, and occasionally spend three generations arguing about who owns a bridge nobody actually wants.`,
    `Magic is real here, but it has terrible manners. It grows in old stones. It collects beneath bridges. It gets into wells, songs, family heirlooms, weather, paperwork, dreams, mushrooms, and once, according to a court record nobody has successfully disproved, an entire flock of geese. Some people study magic for decades. Some inherit it. Some bargain for it. Some trip over it while carrying groceries.`,
    `The green stuff has its own place in all this. Smoke curls from roadside circles where travelers swap stories. Taverns argue over legendary weeds that almost certainly never existed. Enchanted leaf bundles have names like Wizard's Regret, Auntie Moon's Emergency Salad, and Absolutely Not For Horses. Ceremonial fog horns require two people and a written apology. At least one dragon insists the enormous smoking bowl in his cave is a religious artifact and becomes offended if anyone asks which religion.`,
    `North of Mossgate, the land rises into the Goblin Highlands. Green shelves fold beneath gray ridges. Cloudberries grow in pale thickets. Wind cuts through the passes hard enough to steal a hat and then, apparently, keep it. Old timber crossings hang above gorges. Bells carry for miles. At sunset the hills turn gold, then red, then the bruised purple of a place that knows perfectly well darkness is coming.`,
    `People tell stories about the goblins who live there. Goblins are thieves. Goblins are traders. Goblins cannot be trusted. Goblins keep bargains more carefully than kings. Goblins worship roots. Goblins worship bells. Goblins worship nothing except the chance to make somebody else carry something heavy. A merchant in Mossgate will swear a goblin once stole his wagon. A goblin in the Highlands may tell you, with paperwork, that the wagon was repossessed.`,
    `Lately, caravans have come down from the Highlands with black-root marks scratched into crates nobody remembers sending up. Old trails are seeing new traffic. People who normally complain loudly about everything have become strangely quiet about certain shipments. A few travelers have gone missing. A few others returned with stories that do not quite line up.`,
    `That is not your problem yet. Right now you are at Mossgate Wayhouse with a road ahead of you, an empty space where a hero ought to be, and me.`,
    `I'm Eliza. I am your Dungeon Master. You decide who your character is and what they attempt. I handle the world, the people in it, and the rules when the rules matter. If something is obvious, we do not need dice to make it dramatic. If something is uncertain and the outcome matters, I will tell you what is at stake before you roll. If you try something I did not put on a button, tell me anyway. I will not decide what your character feels. That part is yours.`,
    `Mossgate is awake. Somewhere nearby, somebody is shouting about a goat, a missing ladle, and what appears to be a zoning dispute involving an enchanted shrub. Before any of that becomes your problem, tell me your name.`,
  ]),
})
